apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-app
  namespace: trueslu
  selfLink: /apis/apps/v1/namespaces/trueslu/deployments/your-app
  uid: 6d39534a-55a6-49fc-bca2-834f85b4afd5
  resourceVersion: "4886448"
  generation: 3
  creationTimestamp: 2019-07-18T00:57:52Z
  annotations:
    deployment.kubernetes.io/revision: "3"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: your-app
    spec:
      containers:
        - name: your-app
          image: trueslu/logodot-frontend
          ports:
            - name: listen-port
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 3
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Progressing
      status: "True"
      lastUpdateTime: 2019-07-18T01:04:10Z
      lastTransitionTime: 2019-07-18T00:57:52Z
      reason: NewReplicaSetAvailable
      message: ReplicaSet "your-app-694f97fd5b" has successfully progressed.
    - type: Available
      status: "True"
      lastUpdateTime: 2019-07-18T01:14:33Z
      lastTransitionTime: 2019-07-18T01:14:33Z
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
